name: my flow1

concurrency:
  group: w1-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "hello w1"
