name: my flow1

concurrency:
  group: w1-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "hello w1 at ci/test"
          exit 1
