name: w2

concurrency:
  group: w2-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["w1"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "hello w2"
