name: my flow2

concurrency:
  group: w2-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - ci/test

jobs:
  call-flow1:
    uses: ./.github/workflows/1.yaml
    secrets: inherit
  test:
    runs-on: ubuntu-latest
    needs: call-flow1
    steps:
      - name: hello
        run: |
          echo "hello w2,i'm at ci/test"
