name: my flow2

concurrency:
  group: w2-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["my flow1"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "hello w2"
